/* Set this after deploying the Apps Script web app. Leave blank to use demo records. */
const API_URL = '[https://script.google.com/macros/s/AKfycbyr7aOTu7Co7K7rNdTJGdupAlDR0rQfmVV09iwLbr8fMukFKy36nCU28KI48s-3E-RD/exec](https://script.google.com/macros/s/AKfycbyr7aOTu7Co7K7rNdTJGdupAlDR0rQfmVV09iwLbr8fMukFKy36nCU28KI48s-3E-RD/exec)';
const demo = { settings:{siteName:'UNSC Operational Command',heroMessage:'Personnel and operational intelligence, synced live from command.',theater:'SCP:RP'}, announcements:[{date:'2026-08-30',title:'Portal online',body:'The command portal is operational. Check back after each deployment for official intelligence.',priority:'Command',author:'Fleet Command',pinned:'TRUE'}], operations:[{date:'2026-08-30',name:'Command Network Initialization',type:'Deployment',location:'Site Command',status:'Completed',lead:'Fleet Command',summary:'The UNSC operations portal has been established.'}], roster:[{username:'YourUsername',codename:'NOBLE ONE',rank:'Commander',unit:'UNSC Command',status:'Active',joinDate:'2026-08-30'}], morphs:[{id:'marine',label:'UNSC Marine',category:'Infantry',commandTemplate:'run permmorph {username} remove & permshirt {username} 11894121092 13145898306 & permhat {username} 17257920031 89778560377368 18273147965 134473988434908 96010971591840 115183420939671 94892474338365 Iqnvg & permcolornvg {username} 195 210 220 & permrtag {username} <b><font color="#000000" face="Michroma"> [ UNSC ] </font></b><br/><font color="#000000"><font face="Michroma"><i> [ Marine - {codename} | {rank} ] </i></font></font><br/> & permntag {username} <font face="Jura"> 『 {rank} " {codename} ” 』 </font> & startergear {username} M4,Pistol & permmaxhealth {username} 120',description:'Standard UNSC Marine deployment.',active:'TRUE'},{id:'odst',label:'ODST Trooper',category:'Special Forces',commandTemplate:'run permmorph {username} remove & permshirt {username} 11894121092 13145898306 & permhat {username} 17257920031 89778560377368 18273147965 134473988434908 96010971591840 115183420939671 94892474338365 Iqnvg & permcolornvg {username} 195 210 220 & permrtag {username} <b><font color="#000000" face="Michroma">  UNSC  </font></b><br/><font color="#000000"><font face="Michroma"><i>  Marine - {codename} | {rank}  </i></font></font><br/> & permntag {username} <font face="Jura">  {rank} " {codename} ”  </font> & startergear {username} M4,Pistol & permmaxhealth {username} 120',description:'Orbital Drop Shock Trooper configuration.',active:'TRUE'}] };
let state = demo, activeUnit='All', currentCommand='';
const $ = id => document.getElementById(id);
const clean = v => String(v ?? '').trim();
const enabled = v => ['true','yes','1','active'].includes(clean(v).toLowerCase());
const escape = v => clean(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const date = v => { const d=new Date(v); return isNaN(d) ? clean(v) : d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}); };
function render(){ const {settings={},announcements=[],operations=[],roster=[],morphs=[]}=state; document.title=`${settings.siteName||'UNSC'} // Operational Command`; $('heroMessage').textContent=settings.heroMessage||demo.settings.heroMessage; $('theater').textContent=settings.theater||'SCP:RP'; $('metricRoster').textContent=roster.filter(x=>clean(x.status).toLowerCase()!=='inactive').length; $('metricOperations').textContent=operations.length; $('metricAnnouncements').textContent=announcements.length; renderAnnouncements(announcements); renderOperations(operations); renderRoster(roster); renderMorphs(morphs); }
function renderAnnouncements(items){ $('announcementsGrid').innerHTML=items.length?items.slice(0,6).map(x=>`<article class="announcement ${enabled(x.pinned)?'pinned':''}"><span class="tag">${escape(x.priority||'Notice')}</span><h3>${escape(x.title)}</h3><p>${escape(x.body)}</p><footer>${date(x.date)} · ${escape(x.author||'UNSC Command')}</footer></article>`).join(''):$('emptyState').innerHTML; }
function renderOperations(items){ $('operationsList').innerHTML=items.length?items.slice(0,12).map(x=>`<article class="operation"><div class="date">${date(x.date)}</div><div><h3>${escape(x.name)}</h3><small>${escape(x.type||'Operation')} · ${escape(x.location||'Classified')}</small></div><p>${escape(x.lead||'Unassigned')}</p><p>${escape(x.summary||'No summary provided.')}</p><span class="status ${clean(x.status).toLowerCase()}">${escape(x.status||'Pending')}</span></article>`).join(''):$('emptyState').innerHTML; }
function renderRoster(items){ const query=clean($('rosterSearch').value).toLowerCase(); const units=['All',...new Set(items.map(x=>clean(x.unit)).filter(Boolean))]; $('unitFilters').innerHTML=units.map(u=>`<button data-unit="${escape(u)}" class="${u===activeUnit?'active':''}">${escape(u)}</button>`).join(''); $('unitFilters').querySelectorAll('button').forEach(b=>b.onclick=()=>{activeUnit=b.dataset.unit;renderRoster(items)}); const visible=items.filter(x=>(activeUnit==='All'||clean(x.unit)===activeUnit)&&Object.values(x).some(v=>clean(v).toLowerCase().includes(query))); $('rosterGrid').innerHTML=visible.length?visible.map(x=>`<article class="roster"><span class="initial">${escape((x.codename||x.username||'?')[0])}</span><h3>${escape(x.codename||x.username)}</h3><p>${escape(x.rank||'Unranked')}</p><footer>@${escape(x.username)} · ${escape(x.unit||'UNSC')}</footer></article>`).join(''):'<p class="empty">No personnel match that search.</p>'; }
function renderMorphs(items){ const usable=items.filter(x=>enabled(x.active)); $('morphPreset').innerHTML=usable.length?usable.map(x=>`<option value="${escape(x.id)}">${escape(x.label)} — ${escape(x.category||'General')}</option>`).join(''):'<option>No active presets</option>'; $('morphPreset').onchange=updatePresetText; updatePresetText(); }
function updatePresetText(){const p=state.morphs.find(x=>clean(x.id)===$('morphPreset').value); $('presetDescription').textContent=p?.description||'No active morph presets have been published.';}
function generate(){const p=state.morphs.find(x=>clean(x.id)===$('morphPreset').value); if(!p)return; const vals={username:clean($('morphUsername').value),codename:clean($('morphCodename').value),rank:clean($('morphRank').value)}; currentCommand=clean(p.commandTemplate).replace(/\{(username|codename|rank)\}/g,(_,k)=>vals[k]); $('morphResult').textContent=currentCommand; $('copyMorph').disabled=!currentCommand; $('copyFeedback').textContent='Command generated. Verify your details before deploying.';}
$('morphForm').addEventListener('submit',e=>{e.preventDefault();generate()}); $('copyMorph').onclick=async()=>{try{await navigator.clipboard.writeText(currentCommand);$('copyFeedback').textContent='Copied to clipboard — ready to paste in-game.'}catch{$('copyFeedback').textContent='Select and copy the command manually.'}}; $('rosterSearch').oninput=()=>renderRoster(state.roster); $('themeButton').onclick=()=>document.body.classList.toggle('high-contrast');
function jsonp(url){return new Promise((resolve,reject)=>{const cb='unsc_'+Date.now();const s=document.createElement('script');window[cb]=data=>{delete window[cb];s.remove();resolve(data)};s.onerror=()=>reject(new Error('Uplink unavailable'));s.src=`${url}${url.includes('?')?'&':'?'}callback=${cb}`;document.head.append(s);setTimeout(()=>reject(new Error('Uplink timed out')),12000)})}
async function load(){if(!API_URL.startsWith('https://script.google.com/')){render();$('syncStatus').textContent='DEMO MODE';$('lastSync').textContent='LOCAL';return}try{state=await jsonp(API_URL);render();$('syncStatus').textContent='ONLINE';$('lastSync').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}catch(e){render();$('syncStatus').textContent='OFFLINE';$('lastSync').textContent='DEMO DATA'}}load();
